export const routes = {
  home: '/',
  menu: '/menu',
  customCakes: '/custom-cakes',
  about: '/about',
  contact: '/contact',
  search: '/search',
  cart: '/cart',
  checkout: '/checkout',
  checkoutSuccess: '/checkout/success/:id',
  account: '/account',
  accountProfile: '/account/profile',
  accountOrders: '/account/orders',
  accountOrder: '/account/orders/:id',
  accountAddresses: '/account/addresses',
  login: '/login',
  signup: '/signup',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
} as const
